name: Check Code standards

on:
  push:

jobs:
  set-up-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install ruff, black, poetry, poe
        run: |
          sudo apt update
          sudo apt install -y python3-pip
          pip install ruff black poethepoet poetry
      - name: run ruff
        run: |
          ruff check **/*.py
      - name: run ruff format
        run: |
          ruff format **/*.py
