
name: Check Code standards

on:
  push:

jobs:
  set-up-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install ruff
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      -
        name: run ruff
        run: |
          ruff check **/*.py
      -
        name: run ruff format
        run: |
          ruff format **/*.py

